#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
node -e 'console.log("Use repository generator: run the Node sitemap task in CI/CLI")'
echo "Sitemaps are generated by Codex task."
